version: '2'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=secret123!
      - POSTGRES_DB=subscriptions
    ports:
      - '5432:5432'
  
  adminer:
    image: 'adminer:latest'
    ports:
      - '8080:8080'